# SPDX-FileCopyrightText: 2022 Daniele Tentoni <daniele.tentoni.1996@gmail.com
#
# SPDX-License-Identifier: MIT

name: Semantic Release

on:
  push:
    branches:
      - main

jobs:
  test:
    uses: daniele-tentoni/cc-codechecker/.github/workflows/test.yml@main

  release:
    concurrency: release
    runs-on: ubuntu-latest
    needs: ["test"]

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          token: ${{ secrets.GH_TOKEN }}

      - name: Setup Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      # - name: Upgrade pip
        # run: python -m pip install --upgrade pip

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-in-project: true

      - name: Load cached venv
        id: cached-poetry-dependencies
        uses: actions/cache@v2
        with:
          path: .venv
          key: venv-${{ runner.os }}-${{ hashFiles('**/poetry.lock') }}-${{ hashFiles('.github/workflows/test.yml') }}

      - name: Install dependencies
        run: poetry install
        if: steps.cached-poetry-dependencies.outputs.cache-hit != 'true'

      - name: Prepare repo
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "action@github.com"

      - name: Publish
        run: |
          poetry run python -m semantic_release publish -v DEBUG -D commit_author="github-actions <action@github.com>"
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
          REPOSITORY_USERNAME: __token__
          REPOSITORY_PASSWORD: ${{ secrets.PYPI_TOKEN }}
