name: Publish Coverage Report

on:
  workflow_run:
    workflows:
      - "Run Unit Tests"
    types:
      - completed

jobs:
  upload:
    name: Upload Coverage to many services
    runs-on: ubuntu-latest
    if: github.event.workflow_run.event == 'pull_request' && github.event.workflow_run.conclusion == 'success'
    steps:
      - name: Download artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: test.yml
          name: code-coverage-report
          workflow_conclusion: success

      - name: Run Codacy Reporter
        uses: codacy/codacy-coverage-reporter-action@v1
        with:
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
          coverage-reports: .coverage

      - name: Produce HTML report
        run: pytest --cov-report html:cov_html

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4.2.3
        with:
          branch: gh-pages
          folder: cov_html
